require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/events", type: :request do
  let!(:user) { User.create!(name: "Admin", email: "admin@mail.com", password: "password", role: "admin") }

  let(:valid_attributes) do
    {
      title: "Test Event",
      description: "A long enough description",
      location: "NCI",
      date: Date.today,
      time: "12:00",
      capacity: 100,
      user_id: user.id
    }
  end

  let(:invalid_attributes) do
    {
      title: "",
      description: "short",
      location: "",
      date: "",
      time: "",
      capacity: 0,
      user_id: user.id
    }
  end

  before { sign_in user }

  describe "GET /index" do
    it "renders the index page successfully" do
      get events_path
      expect(response).to be_successful
    end

    it "returns JSON" do
      get "/events.json"
      expect(response.content_type).to include("application/json")
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new event" do
        expect {
          post events_path, params: { event: valid_attributes }
        }.to change(Event, :count).by(1)
      end
    end

    context "with invalid parameters" do
      it "does not create an event" do
        expect {
          post events_path, params: { event: invalid_attributes }
        }.not_to change(Event, :count)
      end
    end
  end
end
